# Generated by Django 3.1.1 on 2020-09-07 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_institute_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='domain',
            field=models.CharField(null=True, max_length=7),
            preserve_default=False,
        ),
    ]
