# Generated by Django 3.1.1 on 2020-09-07 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_institute_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
