# Generated by Django 3.1.1 on 2020-09-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userinfo_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='total_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total_novotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='total_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
