# Generated by Django 3.1.1 on 2020-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200911_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-total_upvotes', '-total_downvotes', '-total_novotes']},
        ),
    ]
