# Generated by Django 3.1.1 on 2020-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200911_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='domain',
            field=models.CharField(max_length=56),
        ),
    ]
