# Generated by Django 3.1.1 on 2020-10-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
