# Generated by Django 3.1.1 on 2021-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infolist', '0003_auto_20201015_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100)),
                ('subject_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
