# Generated by Django 3.1.1 on 2020-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20200908_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
