# Generated by Django 3.1.1 on 2020-09-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='report',
            name='cr_line',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
