# Generated by Django 3.1.1 on 2020-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_report_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
