# Generated by Django 3.1.1 on 2020-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20200911_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
