# Generated by Django 3.1.1 on 2020-09-17 05:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200911_1448'),
        ('reporter', '0012_auto_20200911_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InformationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('course', models.CharField(max_length=56)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userinfo')),
            ],
        ),
    ]
