# Generated by Django 3.1.1 on 2020-09-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0016_auto_20200922_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationlist',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
