# Generated by Django 3.1.1 on 2020-09-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200922_0950'),
        ('reporter', '0019_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InformationList',
            new_name='ContactList',
        ),
    ]
