# Generated by Django 3.1.1 on 2020-10-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0020_auto_20200927_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anonymized',
            field=models.BooleanField(default=True),
        ),
    ]
