# Generated by Django 3.1.1 on 2020-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0021_report_anonymized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anonymized',
            field=models.BooleanField(default=True, help_text="CRs don't have Access to Voted Users!"),
        ),
    ]
