# Generated by Django 3.1.1 on 2020-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(blank=True, to='polling.Option'),
        ),
    ]
