# Generated by Django 3.1.1 on 2020-10-02 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_auto_20201002_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
