# Generated by Django 3.1.1 on 2020-10-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200922_0950'),
        ('polling', '0004_poll_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='poll', to='polling.Option'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='polluser', to='profiles.userinfo'),
        ),
    ]
