# Generated by Django 3.1.1 on 2020-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0007_auto_20201003_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
